services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: developer
      POSTGRES_DB: eth-wallet
    ports:
      - "5432:5432"

#  vault:
#    image: hashicorp/vault
#    restart: unless-stopped
#    environment:
#      VAULT_DEV_ROOT_TOKEN_ID: "token"
#      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
#    ports:
#      - "8200:8200"
#    command: "vault server -dev -dev-root-token-id=token"